import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
  authors: [{ name: "Ibnu Choldun", url: "https://ibnucholdun.tech" }],
  openGraph: {
    title: "Home",
  },
};

export default function Home() {
  return <main>Hello World</main>;
}
